"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useCart } from "@/lib/cart";
import AddressSelector from "./AddressSelector";
import type { PaymentData, CardData } from "@/types";

interface CreditCardPaymentProps {
  onSuccess: (data: PaymentData) => void;
  onError: (error: string) => void;
  onProcessingChange?: (processing: boolean) => void;
  deliveryAddress: {
    street: string;
    city: string;
    state: string;
    zip: string;
  };
}

export default function CreditCardPayment({
  onSuccess,
  onError,
  onProcessingChange,
  deliveryAddress,
}: CreditCardPaymentProps) {
  const [loading, setLoading] = useState(false);
  const [cardData, setCardData] = useState<CardData>({
    number: "",
    holderName: "",
    expMonth: "",
    expYear: "",
    cvv: "",
    installments: 1,
    zipCode: "",
    city: "",
    state: "",
  });
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [paymentProcessed, setPaymentProcessed] = useState(false);
  const [selectedAddress, setSelectedAddress] = useState<any>(null);
  const [showAddressSelector, setShowAddressSelector] = useState(false);
  const [installmentOptions, setInstallmentOptions] = useState<
    Array<{ installments: number; amount: number; hasInterest: boolean }>
  >([]);
  const items = useCart((s) => s.items);

  // Calcular opções de parcelamento com juros
  const calculateInstallments = () => {
    const totalAmount = items.reduce(
      (sum, item) => sum + item.price * item.qty,
      0
    );
    const options = [];

    for (let installments = 1; installments <= 12; installments++) {
      let amount = totalAmount;
      let hasInterest = false;

      if (installments <= 3) {
        // 1x a 3x: sem juros
        amount = totalAmount;
        hasInterest = false;
      } else if (installments <= 6) {
        // 4x a 6x: juros baixos (2% ao mês)
        const monthlyRate = 0.02;
        const totalWithInterest =
          totalAmount * Math.pow(1 + monthlyRate, installments);
        amount = totalWithInterest;
        hasInterest = true;
      } else {
        // 7x a 12x: juros altos (4% ao mês)
        const monthlyRate = 0.04;
        const totalWithInterest =
          totalAmount * Math.pow(1 + monthlyRate, installments);
        amount = totalWithInterest;
        hasInterest = true;
      }

      options.push({
        installments,
        amount: amount / installments,
        hasInterest,
      });
    }

    setInstallmentOptions(options);
  };

  const handleSubmit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    setLoading(true);
    onProcessingChange?.(true);

    try {
      const response = await fetch("/api/checkout/pagarme-credit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          items: items.map((item) => ({
            id: item.id,
            name: item.name,
            price: item.price,
            quantity: item.qty,
          })),
          deliveryAddress,
          cardData: {
            number: cardData.number.replace(/\s/g, ""),
            holderName: cardData.holderName,
            expMonth: cardData.expMonth,
            expYear: cardData.expYear,
            cvv: cardData.cvv,
            installments: cardData.installments,
            billingAddress: {
              line1: "Endereço de cobrança",
              zipCode: cardData.zipCode,
              city: cardData.city,
              state: cardData.state,
            },
          },
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Erro ao processar pagamento");
      }

      // Se chegou até aqui, o pagamento foi processado com sucesso
      setPaymentProcessed(true);
      onSuccess(data);
    } catch (error: unknown) {
      onError(
        error instanceof Error ? error.message : "Erro ao processar pagamento"
      );
    } finally {
      setLoading(false);
      onProcessingChange?.(false);
    }
  };

  // Gerar pagamento automaticamente quando o componente for montado
  useEffect(() => {
    if (!autoGenerated && !paymentProcessed && !loading) {
      setAutoGenerated(true);
      // Não processar automaticamente - aguardar preenchimento do formulário
    }
  }, [autoGenerated, paymentProcessed, loading]);

  // Calcular parcelas quando o componente montar
  useEffect(() => {
    calculateInstallments();
  }, [items]);

  // Pré-preencher dados do endereço quando selecionado
  useEffect(() => {
    if (selectedAddress) {
      setCardData((prev) => ({
        ...prev,
        zipCode: selectedAddress.zip,
        city: selectedAddress.city,
        state: selectedAddress.state,
      }));
    }
  }, [selectedAddress]);

  const formatCardNumber = (value: string) => {
    return value
      .replace(/\s/g, "")
      .replace(/(\d{4})(?=\d)/g, "$1 ")
      .substring(0, 19);
  };

  if (paymentProcessed) {
    return (
      <div className="space-y-4">
        <div className="text-center">
          <h3 className="text-lg font-semibold mb-2">Pagamento Aprovado!</h3>
          <p className="text-sm text-green-600">
            Seu pagamento foi processado com sucesso
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-1">
      <div className="text-center">
        <h3 className="text-lg font-semibold mb-1">Cartão de Crédito</h3>
        <p className="text-sm text-muted-foreground">
          {loading
            ? "Processando pagamento..."
            : "Preencha os dados do seu cartão"}
        </p>
      </div>

      {loading && (
        <div className="flex justify-center">
          <div className="animate-spin w-6 h-6 border-2 border-[#F8B075] border-t-transparent rounded-full"></div>
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-3">
        <div>
          <Label htmlFor="cardNumber">Número do Cartão</Label>
          <Input
            id="cardNumber"
            type="text"
            placeholder="0000 0000 0000 0000"
            value={cardData.number}
            onChange={(e) =>
              setCardData({
                ...cardData,
                number: formatCardNumber(e.target.value),
              })
            }
            maxLength={19}
            required
          />
        </div>

        <div>
          <Label htmlFor="holderName">Nome no Cartão</Label>
          <Input
            id="holderName"
            type="text"
            placeholder="Nome como está no cartão"
            value={cardData.holderName}
            onChange={(e) =>
              setCardData({
                ...cardData,
                holderName: e.target.value.toUpperCase(),
              })
            }
            required
          />
        </div>

        <div className="grid grid-cols-3 gap-2">
          <div>
            <Label htmlFor="expMonth">Mês</Label>
            <Input
              id="expMonth"
              type="text"
              placeholder="MM"
              value={cardData.expMonth}
              onChange={(e) =>
                setCardData({
                  ...cardData,
                  expMonth: e.target.value.replace(/\D/g, "").substring(0, 2),
                })
              }
              maxLength={2}
              required
            />
          </div>
          <div>
            <Label htmlFor="expYear">Ano</Label>
            <Input
              id="expYear"
              type="text"
              placeholder="AAAA"
              value={cardData.expYear}
              onChange={(e) =>
                setCardData({
                  ...cardData,
                  expYear: e.target.value.replace(/\D/g, "").substring(0, 4),
                })
              }
              maxLength={4}
              required
            />
          </div>
          <div>
            <Label htmlFor="cvv">CVV</Label>
            <Input
              id="cvv"
              type="text"
              placeholder="000"
              value={cardData.cvv}
              onChange={(e) =>
                setCardData({
                  ...cardData,
                  cvv: e.target.value.replace(/\D/g, "").substring(0, 3),
                })
              }
              maxLength={3}
              required
            />
          </div>
        </div>

        <div>
          <Label htmlFor="installments">Parcelas</Label>
          <select
            id="installments"
            className="w-full p-2 border rounded-md"
            value={cardData.installments}
            onChange={(e) =>
              setCardData({
                ...cardData,
                installments: parseInt(e.target.value) || 1,
              })
            }
            required
          >
            {installmentOptions.map((option) => (
              <option key={option.installments} value={option.installments}>
                {option.installments}x de R$ {option.amount.toFixed(2)}
                {option.hasInterest ? " (com juros)" : " (sem juros)"}
              </option>
            ))}
          </select>
        </div>

        <AddressSelector
          onAddressSelect={setSelectedAddress}
          onAddressChange={() => setShowAddressSelector(!showAddressSelector)}
          selectedAddress={selectedAddress}
        />

        {/* Informações sobre parcelamento */}
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 text-sm">
          <h4 className="font-medium text-blue-900 mb-2">
            💳 Condições de Parcelamento
          </h4>
          <div className="space-y-1 text-blue-800">
            <p>
              • <strong>1x a 3x:</strong> Sem juros
            </p>
            <p>
              • <strong>4x a 6x:</strong> Juros de 2% ao mês
            </p>
            <p>
              • <strong>7x a 12x:</strong> Juros de 4% ao mês
            </p>
          </div>
        </div>
      </form>
    </div>
  );
}
