"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { useCart } from "@/lib/cart";
import { useSession } from "next-auth/react";
import type { PaymentData } from "@/types";

interface PixPaymentProps {
  onSuccess: (data: PaymentData) => void;
  onError: (error: string) => void;
  deliveryAddress: {
    street: string;
    city: string;
    state: string;
    zip: string;
  };
  shippingInfo?: {
    rateCents: number;
    rateReais: number;
    distanceKm: number;
    estimatedDays: number;
  };
}

export default function PixPayment({
  onSuccess,
  onError,
  deliveryAddress,
  shippingInfo,
}: PixPaymentProps) {
  const { data: session, status } = useSession();
  const [loading, setLoading] = useState(false);
  const [pixData, setPixData] = useState<PaymentData | null>(null);
  const [checkingPayment, setCheckingPayment] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const items = useCart((s) => s.items);

  // Verificar se o usuário está logado
  if (status === "loading") {
    return (
      <div className="text-center">
        <div className="animate-spin w-8 h-8 border-2 border-orange-500 border-t-transparent rounded-full mx-auto mb-4"></div>
        <p className="text-gray-600">Verificando autenticação...</p>
      </div>
    );
  }

  if (status === "unauthenticated") {
    return (
      <div className="text-center space-y-4">
        <div className="bg-red-50 border border-red-200 rounded-lg p-4">
          <h3 className="font-semibold text-red-800 mb-2">Login Necessário</h3>
          <p className="text-red-700 text-sm">
            Você precisa fazer login para realizar o pagamento PIX.
          </p>
        </div>
        <Button
          onClick={() => (window.location.href = "/login")}
          className="w-full bg-orange-500 hover:bg-orange-600 text-white"
        >
          Fazer Login
        </Button>
      </div>
    );
  }

  const handlePixPayment = async () => {
    setLoading(true);
    try {
      console.log("🔄 Iniciando pagamento PIX...");
      console.log("📦 Items:", items);
      console.log("📍 Endereço:", deliveryAddress);
      console.log("🚚 Frete:", shippingInfo);

      const response = await fetch("/api/checkout/mercadopago-pix", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          items: items.map((item) => ({
            id: item.id,
            name: item.name,
            price: item.price,
            quantity: item.qty,
          })),
          deliveryAddress,
          shippingInfo,
        }),
      });

      console.log("📡 Response status:", response.status);
      console.log(
        "📡 Response headers:",
        Object.fromEntries(response.headers.entries())
      );

      const data = await response.json();
      console.log("📡 Response data:", data);

      if (!response.ok) {
        const errorMessage =
          data.message || data.error || "Erro ao processar pagamento PIX";
        console.error("❌ Erro no pagamento:", errorMessage);
        throw new Error(errorMessage);
      }

      // Verificar se é erro de PIX não habilitado
      if (data.error === "PIX_NOT_ENABLED") {
        const errorMsg = `${data.message}\n\n${data.details || ""}`;
        onError(errorMsg);
        return;
      }

      if (!data.pixQrCode && !data.pixQrCodeUrl) {
        console.error("❌ QR Code não foi gerado");
        throw new Error("QR Code PIX não foi gerado");
      }

      console.log("✅ QR Code gerado com sucesso!");
      console.log("🔗 QR Code URL:", data.pixQrCodeUrl);
      console.log("📝 QR Code Text:", data.pixQrCode);

      setPixData(data);
      setCheckingPayment(true);
    } catch (error: unknown) {
      console.error("❌ Erro completo:", error);
      onError(
        error instanceof Error ? error.message : "Erro ao processar pagamento"
      );
    } finally {
      setLoading(false);
    }
  };

  const checkPaymentStatus = async () => {
    if (!pixData?.orderId) return;

    try {
      const response = await fetch(`/api/checkout/status/${pixData.orderId}`);
      const status = await response.json();

      if (status.paid) {
        setCheckingPayment(false);
        onSuccess(pixData);
      }
    } catch (error) {
      console.error("Erro ao verificar pagamento:", error);
    }
  };

  // Gerar PIX automaticamente quando o componente for montado
  useEffect(() => {
    if (!autoGenerated && !pixData && !loading) {
      setAutoGenerated(true);
      handlePixPayment();
    }
  }, [autoGenerated, pixData, loading]);

  // Polling para verificar status do pagamento
  useEffect(() => {
    if (!checkingPayment || !pixData) return;

    const interval = setInterval(checkPaymentStatus, 3000); // Verifica a cada 3 segundos
    return () => clearInterval(interval);
  }, [checkingPayment, pixData]);

  if (pixData) {
    return (
      <div className="space-y-4 animate-fade-in">
        <div className="text-center">
          <p className="sol-text-secondary text-lg font-medium">
            Escaneie o QR Code ou copie o código PIX
          </p>
        </div>

        {/* QR Code Image - Direto na página */}
        {pixData.pixQrCodeUrl ? (
          <div className="flex justify-center p-6 bg-white rounded-xl border-2 border-gray-200 shadow-lg">
            <img
              src={pixData.pixQrCodeUrl}
              alt="QR Code PIX"
              className="w-72 h-72 rounded-lg"
            />
          </div>
        ) : (
          <div className="text-center p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
            <p className="text-yellow-700 text-sm">QR Code não disponível</p>
            <p className="text-yellow-600 text-xs mt-1">
              Aguarde alguns instantes ou tente novamente
            </p>
          </div>
        )}

        {/* Copy PIX Code Button */}
        {pixData.pixQrCode && (
          <div className="space-y-2">
            <Button
              variant="secondary"
              size="lg"
              onClick={async () => {
                try {
                  await navigator.clipboard.writeText(pixData.pixQrCode || "");
                  alert("✅ Código PIX copiado! Cole no seu app do banco.");
                } catch (error) {
                  console.error("Erro ao copiar:", error);
                  // Fallback: mostrar o código para copiar manualmente
                  alert(`Copie este código: ${pixData.pixQrCode}`);
                }
              }}
              className="w-full bg-sol-orange hover:bg-sol-orange-dark text-white font-semibold py-3"
            >
              📋 Copiar Código PIX
            </Button>
            <p className="sol-text-secondary text-xs text-center">
              Cole este código no app do seu banco para pagar
            </p>
          </div>
        )}

        {/* Order Info */}
        <div className="bg-gray-50 rounded-lg p-4 text-center space-y-2">
          <p className="text-gray-700 font-semibold">
            Valor: <span className="text-sol-orange">R$ {pixData.total.toFixed(2)}</span>
          </p>
          <p className="text-gray-600 text-sm">
            Expira em: {Math.floor((pixData.expiresIn || 1800) / 60)} minutos
          </p>
        </div>

        {/* Payment Status */}
        {checkingPayment && (
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 text-center">
            <div className="animate-spin w-6 h-6 border-3 border-sol-orange border-t-transparent rounded-full mx-auto mb-3"></div>
            <p className="text-blue-700 font-medium text-sm">
              Aguardando confirmação do pagamento...
            </p>
            <p className="text-blue-600 text-xs mt-2">
              Pague o PIX e aguarde alguns instantes. Você será redirecionado automaticamente.
            </p>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="text-center">
        <h3 className="sol-title-secondary mb-2">Pagamento PIX</h3>
        <p className="sol-text-secondary">
          {loading
            ? "Gerando QR Code PIX..."
            : "Pague instantaneamente com PIX"}
        </p>
      </div>

      {loading && (
        <div className="flex justify-center">
          <div className="animate-spin w-8 h-8 border-2 border-sol-orange border-t-transparent rounded-full"></div>
        </div>
      )}

      {!loading && (
        <Button
          onClick={handlePixPayment}
          className="w-full bg-sol-orange hover:bg-sol-orange-dark text-white"
        >
          Abrir Checkout PIX
        </Button>
      )}
    </div>
  );
}
